//! Worktree listing and manipulation.

use std::path::{Path, PathBuf};
use std::time::Duration;

use super::branch::is_safe_branch_name;
use super::{GitError, GitService};

/// Timeout for `git worktree add`, which can take a long time on large
/// repositories because it writes the full working tree.
const WORKTREE_ADD_TIMEOUT: Duration = Duration::from_secs(300);

/// Prefix used for auto-generated temporary worktree branches.
pub const TEMP_WORKTREE_BRANCH_PREFIX: &str = "devinorium";

/// Pattern matching a temporary worktree branch generated by this backend.
pub const TEMP_WORKTREE_BRANCH_PATTERN: &str = r"^devinorium/[0-9a-f]{8}$";

/// A worktree.
#[derive(Debug, Clone, serde::Serialize)]
pub struct Worktree {
    pub path: PathBuf,
    pub head: String,
    pub branch: Option<String>,
    pub is_main: bool,
}

/// Generate a temporary worktree branch name such as `devinorium/abc12345`.
pub fn temporary_worktree_branch_name() -> String {
    let token: u32 = rand::random();
    format!("{TEMP_WORKTREE_BRANCH_PREFIX}/{token:08x}")
}

/// Convert a branch name into a safe directory name. Slashes become dashes
/// and leading dots are stripped so the path is not hidden inside the parent.
pub fn sanitize_branch_for_path(branch: &str) -> String {
    let mut out = branch.replace(['/', '\\'], "-").trim().to_string();
    while out.starts_with('.') {
        out = out[1..].to_string();
    }
    if out.is_empty() {
        out = "worktree".to_string();
    }
    out
}

/// Return the managed worktree directory for a repo and branch.
///
/// Worktrees are kept in a hidden sibling directory so they do not live
/// inside the main working tree and risk being nested.
pub fn managed_worktree_path(toplevel: &Path, branch: &str) -> PathBuf {
    let dir_name = toplevel
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "repo".to_string());
    let parent = toplevel.parent().unwrap_or(toplevel);
    let worktrees_root = parent.join(format!(".{dir_name}-worktrees"));
    worktrees_root.join(sanitize_branch_for_path(branch))
}

/// Check whether a branch name was generated by [temporary_worktree_branch_name].
pub fn is_temporary_worktree_branch(branch: &str) -> bool {
    let re = regex::Regex::new(TEMP_WORKTREE_BRANCH_PATTERN).expect("valid regex");
    re.is_match(branch.trim())
}

/// Worktree names are used as filesystem directory names, so we disallow
/// path separators entirely to prevent traversal.
pub(super) fn is_safe_worktree_name(name: &str) -> bool {
    if !is_safe_branch_name(name) {
        return false;
    }
    if name.contains('/') || name.contains('\\') {
        return false;
    }
    true
}

impl GitService {
    /// Return worktrees. When `force` is true, re-list worktrees from git.
    pub async fn worktrees(&self, path: &Path, force: bool) -> Result<Vec<Worktree>, GitError> {
        let status = self.repo_status(path, force).await?;
        if !status.is_repo {
            return Err(GitError::NotRepo);
        }
        let key = path.to_string_lossy().to_string();
        if force {
            self.worktree_cache.invalidate(&key);
        }
        if let Some(worktrees) = self.worktree_cache.get(&key) {
            return Ok(worktrees);
        }
        let worktrees = self.list_worktrees(path).await?;
        self.worktree_cache.insert(key, worktrees.clone());
        Ok(worktrees)
    }

    /// Create a worktree at an explicit path, optionally creating a new branch.
    pub async fn create_worktree_at(
        &self,
        path: &Path,
        branch_name: &str,
        base: &str,
        worktree_path: &Path,
        new_branch: bool,
    ) -> Result<Worktree, GitError> {
        self.repo_status(path, false).await?;

        if branch_name.trim().is_empty() {
            return Err(GitError::Other("branch name is required".to_string()));
        }
        if !is_safe_branch_name(branch_name) {
            return Err(GitError::Other("invalid branch name".to_string()));
        }
        if base.trim().is_empty() {
            return Err(GitError::Other("base branch is required".to_string()));
        }

        if let Some(parent) = worktree_path.parent() {
            if let Err(e) = tokio::fs::create_dir_all(parent).await {
                return Err(GitError::Other(format!("failed to create parent: {e}")));
            }
        }
        match tokio::fs::try_exists(worktree_path).await {
            Ok(true) => return Err(GitError::Other("worktree path already exists".to_string())),
            Ok(false) => {}
            Err(e) => return Err(GitError::Other(format!("filesystem error: {e}"))),
        }

        let mut cmd = self.git_cmd(path);
        cmd.arg("worktree").arg("add");
        if new_branch {
            cmd.arg("-b").arg(branch_name);
        }
        cmd.arg(worktree_path).arg(base);
        self.run(&mut cmd, WORKTREE_ADD_TIMEOUT).await?;

        // `git worktree add` leaves submodules empty. The objects are normally
        // already in the parent's `.git/modules`, so this is fast and offline
        // for existing clones. A first-ever clone may need the network, and a
        // submodule that cannot be fetched must not roll back this operation.
        if worktree_path.join(".gitmodules").exists() {
            let mut sub = self.git_cmd(worktree_path);
            sub.args(["submodule", "update", "--init", "--recursive"]);
            if let Err(e) = self.run(&mut sub, WORKTREE_ADD_TIMEOUT).await {
                tracing::warn!(error = %e, "worktree submodule update failed");
            }
        }

        self.invalidate(path);

        // Resolve the actual worktree.
        let worktrees = self.list_worktrees(path).await?;
        worktrees
            .into_iter()
            .find(|w| w.path == worktree_path)
            .ok_or_else(|| GitError::Other("failed to resolve new worktree".to_string()))
    }

    /// Create a worktree, optionally creating a new branch.
    pub async fn create_worktree(
        &self,
        path: &Path,
        name: &str,
        base: &str,
        new_branch: bool,
    ) -> Result<Worktree, GitError> {
        if !is_safe_worktree_name(name) {
            return Err(GitError::Other("invalid worktree name".to_string()));
        }
        let worktree_path = path.join(name);
        self.create_worktree_at(path, name, base, &worktree_path, new_branch)
            .await
    }

    /// Remove a worktree at `worktree_path`.
    pub async fn remove_worktree(&self, path: &Path, worktree_path: &Path) -> Result<(), GitError> {
        self.repo_status(path, false).await?;

        let worktrees = self.list_worktrees(path).await?;
        let target = worktrees
            .into_iter()
            .find(|w| w.path == worktree_path)
            .ok_or_else(|| GitError::Other("worktree not found".to_string()))?;
        if target.is_main {
            return Err(GitError::Other(
                "cannot remove the main worktree".to_string(),
            ));
        }

        let mut cmd = self.git_cmd(path);
        cmd.arg("worktree")
            .arg("remove")
            .arg("--force")
            .arg(worktree_path);
        self.run(&mut cmd, Duration::from_secs(15)).await?;

        self.invalidate(path);
        Ok(())
    }

    async fn list_worktrees(&self, path: &Path) -> Result<Vec<Worktree>, GitError> {
        let out = self
            .run_with(
                path,
                &["worktree", "list", "--porcelain", "-z"],
                Duration::from_secs(5),
            )
            .await?;
        Ok(parse_worktrees(&out))
    }
}

/// Parse `git worktree list --porcelain -z` output.
pub(super) fn parse_worktrees(output: &str) -> Vec<Worktree> {
    let mut worktrees = Vec::new();
    let mut path_buf = None;
    let mut head = String::new();
    let mut branch = None;

    for token in output.split('\0') {
        if token.is_empty() {
            continue;
        }
        if token.starts_with("worktree ") {
            if let Some(p) = path_buf.take() {
                // The first worktree listed by `git worktree list` is always
                // the main (original) worktree.
                let is_main = worktrees.is_empty();
                worktrees.push(Worktree {
                    path: p,
                    head: head.clone(),
                    branch: branch.clone(),
                    is_main,
                });
            }
            path_buf = Some(PathBuf::from(token.split_at(9).1));
            head.clear();
            branch = None;
        } else if token.starts_with("HEAD ") {
            head = token.split_at(5).1.to_string();
        } else if token.starts_with("branch ") {
            let raw = token.split_at(7).1;
            let short = raw.strip_prefix("refs/heads/").unwrap_or(raw);
            branch = Some(short.to_string());
        }
    }

    if let Some(p) = path_buf {
        let is_main = worktrees.is_empty();
        worktrees.push(Worktree {
            path: p,
            head,
            branch,
            is_main,
        });
    }

    worktrees
}

#[cfg(test)]
mod tests {
    use super::is_temporary_worktree_branch;
    use super::{
        is_safe_worktree_name, managed_worktree_path, parse_worktrees, sanitize_branch_for_path,
        temporary_worktree_branch_name,
    };

    #[test]
    fn is_safe_worktree_name_rejects_path_separators() {
        assert!(is_safe_worktree_name("feature"));
        assert!(!is_safe_worktree_name("foo/bar"));
        assert!(!is_safe_worktree_name("foo\\bar"));
        assert!(!is_safe_worktree_name("../escape"));
    }

    #[test]
    fn parse_worktrees_lists_main_first() {
        let out =
            "worktree /repo\0HEAD abc123\0branch refs/heads/main\0worktree /repo.wt\0HEAD def456\0";
        let worktrees = parse_worktrees(out);
        assert_eq!(worktrees.len(), 2);
        assert_eq!(worktrees[0].path, std::path::PathBuf::from("/repo"));
        assert!(worktrees[0].is_main);
        assert_eq!(worktrees[0].branch.as_deref(), Some("main"));
        assert_eq!(worktrees[1].path, std::path::PathBuf::from("/repo.wt"));
        assert!(!worktrees[1].is_main);
    }

    #[test]
    fn temporary_branch_name_matches_pattern() {
        let name = temporary_worktree_branch_name();
        assert!(is_temporary_worktree_branch(&name));
        assert!(!is_temporary_worktree_branch("feature/foo"));
    }

    #[test]
    fn sanitize_branch_for_path_replaces_separators() {
        assert_eq!(
            sanitize_branch_for_path("devinorium/abc12345"),
            "devinorium-abc12345"
        );
        assert_eq!(sanitize_branch_for_path("feature\\foo"), "feature-foo");
        assert_eq!(sanitize_branch_for_path(".hidden"), "hidden");
    }

    #[test]
    fn managed_worktree_path_is_outside_repo() {
        let path = std::path::PathBuf::from("/home/user/project");
        let wt = managed_worktree_path(&path, "devinorium/abc12345");
        assert_eq!(
            wt,
            std::path::PathBuf::from("/home/user/.project-worktrees/devinorium-abc12345")
        );
    }
}
